// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rungeKutta
NumericMatrix rungeKutta(double t0, NumericVector y0, double h, int n, double g, double c, double m);
RcppExport SEXP _SA22231079_rungeKutta(SEXP t0SEXP, SEXP y0SEXP, SEXP hSEXP, SEXP nSEXP, SEXP gSEXP, SEXP cSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(rungeKutta(t0, y0, h, n, g, c, m));
    return rcpp_result_gen;
END_RCPP
}
// eulerMethod
NumericMatrix eulerMethod(double t0, NumericVector y0, double h, int n, double g, double c, double m);
RcppExport SEXP _SA22231079_eulerMethod(SEXP t0SEXP, SEXP y0SEXP, SEXP hSEXP, SEXP nSEXP, SEXP gSEXP, SEXP cSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type t0(t0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< double >::type c(cSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(eulerMethod(t0, y0, h, n, g, c, m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA22231079_rungeKutta", (DL_FUNC) &_SA22231079_rungeKutta, 7},
    {"_SA22231079_eulerMethod", (DL_FUNC) &_SA22231079_eulerMethod, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA22231079(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
