# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title the fourth-order Runge-Kutta 
#' @description the fourth-order Runge-Kutta method for solving a system of differential equations
#' @param t0 initial t value
#' @param y0 initial y values
#' @param h step size
#' @param n number of iterations
#' @param g gravity acceleration
#' @param c air resistance coefficient
#' @param m object mass
#' @return the result of the solution
#' @examples
#' \dontrun{
#' rnC = rungeKutta(t0 = 0, y0 = 0, h = 0.0002, n = 10000, g = 9.8, c = 0.5, m = 1.0)
#' }
#' @export
rungeKutta <- function(t0, y0, h, n, g, c, m) {
    .Call('_SA22231079_rungeKutta', PACKAGE = 'SA22231079', t0, y0, h, n, g, c, m)
}

#' @title the fourth-order eulerMethod
#' @description the fourth-order eulerMethod method for solving a system of differential equations
#' @param t0 initial t value
#' @param y0 initial y values
#' @param h step size
#' @param n number of iterations
#' @param g gravity acceleration
#' @param c air resistance coefficient
#' @param m object mass
#' @return the result of the solution
#' @examples
#' \dontrun{
#' rnC = eulerMethod(t0 = 0, y0 = 0, h = 0.0002, n = 10000, g = 9.8, c = 0.5, m = 1.0)
#' }
#' @export
eulerMethod <- function(t0, y0, h, n, g, c, m) {
    .Call('_SA22231079_eulerMethod', PACKAGE = 'SA22231079', t0, y0, h, n, g, c, m)
}

